### ISSUE TITLE
Export images doesn't work

### ISSUE THREAD

**Issue by linkmadao** [Kaplas80/TranslationFramework2#23]
When i use the exported images in newer version of this software, this is the result:
![image](https://user-images.githubusercontent.com/6817344/107153608-38b95380-694d-11eb-868e-3761f9432a57.png)

Using older version:
![image](https://user-images.githubusercontent.com/6817344/107153845-6a7eea00-694e-11eb-9639-4f1455c6e70a.png)

This is how this images are exibed:

Left -> image exported in the older version of software
Right -> image exported in the newer version of software
![image](https://user-images.githubusercontent.com/6817344/107153538-d95b4380-694c-11eb-8904-f094fae11316.png)

**Comment by Kaplas80** [comment]
Hi!

The image management in the app have not changed in months (probably more than a year). I've just tried to export the same file with the latest app and it works for me:

![image](https://user-images.githubusercontent.com/5345429/107154878-8c3f9780-6975-11eb-8c4d-6f27196e62c7.png)

Are you exporting from the original game files or modified ones?

**Comment by linkmadao** [comment]
I'm exporting from the original game files with automatic and manual method.

**Comment by Kaplas80** [comment]
Hi!

Did you manage to export the textures correctly?

**Comment by linkmadao** [comment]
No, you still have the same problem. I tested it on other computers and the same result happens.

PS: I always use the most current version of your code.

**Comment by Kaplas80** [comment]
I still think that the problem is that your game files are corrupted.

I'd try to verify them with steam and then create a new translation project with the app, just to check if the export in that case is ok.

Anyway, if you upload any of the wrong images to mega (or wetransfer or other upload service), I can take a look and check if I can find the problem.

**Comment by linkmadao** [comment]
So, the problem doesn't just happen with my game, I already uninstalled and downloaded it several times and it keeps happening, and I always tested it by creating new projects.

I have already asked other members of my team to take the test and the same thing happens.

This happened on Yakuza 0 and Yakuza Kiwami, so I think it is something related to the code itself.

**Comment by Kaplas80** [comment]
Well, then please upload any of the wrong image files, so I can check it.

**Comment by linkmadao** [comment]
[ifc_jimaku_majima.zip](https://github.com/Kaplas80/TranslationFramework2/files/6057498/ifc_jimaku_majima.zip)

**Comment by Kaplas80** [comment]
But that's a translated image, not an original one:

![image](https://user-images.githubusercontent.com/5345429/109429130-8845e900-79fa-11eb-8673-b7637fe65a44.png)

I think that you're saving it with a wrong compression. The original is DXT5 and yours is ARGB, I don't know if the game can read that format.

Original:
![image](https://user-images.githubusercontent.com/5345429/109429343-9c3e1a80-79fb-11eb-809d-fd37538b3a50.png)

Yours:
![image](https://user-images.githubusercontent.com/5345429/109429363-ac55fa00-79fb-11eb-818a-86c8cbeceb55.png)

**Comment by linkmadao** [comment]
I send the wrong file, sorry.

[ifc_jimaku_majima.zip](https://github.com/Kaplas80/TranslationFramework2/files/6057739/ifc_jimaku_majima.zip)

Both this and the previous file were exported by your software. If I import them, the error happens.

**Comment by Kaplas80** [comment]
You are right: my app is exporting the images as ARGB. It is very rare, because the last change in Yakuza's DDS manager is from 2019, and we haven't noticed this behaviour until now.

I'm thinking in 2 possible solutions:
1. You can try to convert the dds files to DXT1 or DXT5 and import them with the app. I'm 99% sure that it will work.
2. You can change every `typeof(DDSFile)` with `typeof(DDS2File)` in [Game.cs](https://github.com/Kaplas80/TranslationFramework2/blob/master/src/Plugins/TFGame.YakuzaKiwami/Game.cs). It will use my latest DDS manager. It exports the images as PNG and converts them to the right format when importing. The problem is that it is incompatible with previous projects, so I'm not sure with merging those changes in the main branch.

**Comment by Kaplas80** [comment]
I've changed the type from `DDSFile` to `DDS2File`. It's a __breaking change__ and it won't work with existing projects.

To update a existing project, you have to:
1. Export all texts to Po format before updating the app
2. Update the app
3. Create a new translation project
4. Import previous exported texts.
