### ISSUE TITLE
AI The Somnium Files Switch Version

### ISSUE THREAD

**Issue by foubou** [Kaplas80/TranslationFramework2#30]
I was able to implement the translation files to PC but how to apply the translation to Switch ? Is there a specific method or a tuto to implement the translation in the Switch version ?

**Comment by Kaplas80** [comment]
The method is the same than in PC:

1. Get the game files from the console.
2. Create a new translation project.
3. Translate.
4. Build the translated files.
5. Replace files in the console.

If your question is how to do steps 1 and 5, I can't help you, because I don't have a Nintendo Switch. Other user confirmed that it works.

**Comment by foubou** [comment]
Thank you very much !
